### PR TITLE
[Feature] - API proxy

### PR DESCRIPTION
**Pull request by Quentinchampenois**
#### Description

Refactor cities autocompletion to reduce API requests.

When not registered, API rate limit is set to 500. This PR allows to define authorization key to have a rate limit equals to 20000/day.

Also, API calls are now performed from backend and response are store in Cache to perform once a request for a given zipcode

#### How to test

* Generate a development_app `bundle exec rake development_app`
* Login as user or admin
* Go to My profile > authorizations
* Select Additional informations
* Type a zipcode and see list refreshed

#### Env vars

`OPENDATASOFT_API_KEY`: If define perform API calls with key

### CODE REVIEW

**Comment by Quentinchampenois** [comment]
I don't know why Webpacker does not compile in CI, I wonder if the NPM cache does not use a old version of package with missing dependencies

**Review by AyakorK — APPROVED** [review]

**Review by armandfardeau — CHANGES_REQUESTED** [review]
Hello thanks for your contribution !

Could you please fix the failing CI workflow?

It's related to https://github.com/decidim/decidim/issues/10993

**Comment by Quentinchampenois** [comment]
Yes but solution seems to be removing a part of the `babel.config.json` in generated test_app so I am not sure about the solution

**Comment by armandfardeau** [comment]
> Yes but solution seems to be removing a part of the `babel.config.json` in generated test_app so I am not sure about the solution

Yes until decidim backports the fix or this module is upgrade to 0.27

**Review by armandfardeau — APPROVED** [review]

**Pull request merged**
